# Generated by Django 2.2.2 on 2019-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=10, null=True)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
